# Generated by Django 5.0.2 on 2024-04-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SongPost",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sampler_title", models.CharField(max_length=100)),
                ("sampled_title", models.CharField(max_length=100)),
                ("sampler_album", models.CharField(max_length=100)),
                ("sampled_album", models.CharField(max_length=100)),
                ("sampler_artist", models.CharField(max_length=100)),
                ("sampled_artist", models.CharField(max_length=100)),
                ("sampler_artwork", models.URLField()),
                ("sampled_artwork", models.URLField()),
                ("sampler_audio", models.URLField()),
                ("sampled_audio", models.URLField()),
                ("sampler_year", models.IntegerField()),
                ("sampled_year", models.IntegerField()),
                ("post_date", models.DateField(unique=True)),
            ],
        ),
    ]
