# Generated by Django 5.0.2 on 2024-04-18 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Member",
        ),
    ]
